### ISSUE TITLE
Not able to work with "AWS" model providers.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/anthropic-provider#3]
**Steps to reproduce the problem:**

1. Have all the AWS related env variables set
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
AWS_SESSION_TOKEN
AWS_REGION
2. Execute gptscript using AWS model - `gptscript --disable-cache --debug --default-model='anthropic.claude-3-sonnet-20240229-v1:0 from github.com/gptscript-ai/anthropic-provider' examples/bob.gpt`
3. When prompted to pick a provider , pick AWS.
4. After this it fails with "Please authenticate with AWS." error
```
Please pick a model provider: AWS or Anthropic.
? provider AWS
{
  "cached": false,
  "completionID": "1",
  "id": "1",
  "level": "debug",
  "logger": "/pkg/monitor",
  "msg": "messages",
  "parentID": "",
  "response": {
    "err": null,
    "output": "{\"provider\":\"AWS\"}"
  },
  "time": "2024-04-18T16:49:38-07:00",
  "toolID": "sys.prompt"
}
{
  "id": "1",
  "level": "info",
  "logger": "/pkg/monitor",
  "msg": "ended    [main]",
  "output": "{\"provider\":\"AWS\"}",
  "parentID": "",
  "time": "2024-04-18T16:49:38-07:00",
  "toolID": "sys.prompt"
}
{
  "err": null,
  "level": "debug",
  "logger": "/pkg/monitor",
  "msg": "Run stopped",
  "output": "{\"provider\":\"AWS\"}",
  "runID": "1",
  "time": "2024-04-18T16:49:38-07:00"
}
Please authenticate with AWS.
{"env": {"AWS": "true"}}
: exit status 1
```

 **Expected Behavior**:
We should be able to work with AWS models.

**Comment by drpebcak** [comment]
Pushed a fix for this already.

**Comment by sangee2004** [comment]
Able to work with AWS models successfully.
