### ISSUE TITLE
Should be able to work with both "AWS" and "Anthropic" providers without having to manually delete existing credentials.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/anthropic-provider#4]
**Steps to reproduce the problem:**
1. Execute gptscript using anthropic model provider - `gptscript --disable-cache --debug --default-model='claude-3-opus-20240229 from github.com/gptscript-ai/anthropic-provider' examples/bob.gpt`  
2. This results in user being prompted for token and a credential - `github.com/gptscript-ai/anthropic-provider/credential` gets created.
3. Execute gptscript using aws model provider - `gptscript --disable-cache --debug --default-model='anthropic.claude-3-sonnet-20240229-v1:0 from from github.com/gptscript-ai/anthropic-provider' examples/bob.gpt`

This script will fail with `anthropic.PermissionDeniedError: Error code: 403 - {'message': "You don't have access to the model with the specified model ID."} ` error.

**Expected Behavior:**
User should be prompted for a model and he should be able to set "AWS" and be able to execute scripts successfully using the AWS env variables that have been set .

**Note** - When I delete the credentials that was created in step 2 , then user is prompted to set model provider and work with AWS models successfully.

**Comment by drpebcak** [comment]
This is not something the provider can fix.. this issue should be moved to gptscript because its an issue with the credential implementation. It's not really a bug either, it would be an enhancement.

**Comment by sangee2004** [comment]
Would we not be able to create 2 different credential entries for "AWS" vs "Anthropic" something  like `github.com/gptscript-ai/anthropic-provider/aws/credential` and `github.com/gptscript-ai/anthropic-provider/anthropic/credential` so that they can co exist and operate independently ?

**Comment by drpebcak** [comment]
No, because how would you call those separately when using the anthropic provider?

**Comment by sangee2004** [comment]
Docs mention that multiple credentials can be provided for a tool. I will move this issue to `gptscript` repo.

**Comment by sangee2004** [comment]
Logged https://github.com/gptscript-ai/gptscript/issues/267 to track this issue.
